"""create user & edit message table

Revision ID: 69b2271d1176
Revises: be3c9b4a1601
Create Date: 2025-09-08 18:19:25.331938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69b2271d1176'
down_revision: Union[str, Sequence[str], None] = 'be3c9b4a1601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('messages', 'user_id',
               existing_type=sa.VARCHAR(),
               type_=sa.dialects.postgresql.UUID(as_uuid=True),
               postgresql_using="user_id::uuid",
               existing_nullable=True)
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.create_foreign_key(None, 'messages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    op.alter_column('messages', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_table('users')
    # ### end Alembic commands ###
