"""add unique constraint on document name

Revision ID: d6acf13b696e
Revises: 8acf2760b6a7
Create Date: 2025-08-25 09:25:56.377253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6acf13b696e'
down_revision: Union[str, Sequence[str], None] = '8acf2760b6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'documents', ['size'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='unique')
    # ### end Alembic commands ###
